# Use classic node_modules linker instead of PnP
nodeLinker: node-modules

# Optional: allow rebuilding native modules
enableImmutableInstalls: false

yarnPath: .yarn/releases/yarn-4.5.0.cjs
compressionLevel: mixed
enableGlobalCache: false
enableTelemetry: false
supportedArchitectures:
  os: ["linux"]
  cpu: ["x64", "arm64"]
